

<body>
    <!-- Start Header Section -->
    <div class="searchmls">
        <div class="container">
            <div class="mls-text">
                <div class="overlay">
                    <div class="cover">
                        <div class="section-1">
                            <span class="search-title">Search MLS</span>
                            <div class="search-box right">
                                <select name="sLangCode" class="TDProfileText" onchange="ChangeLang('ENGLISH')" style="width: 150px;">
                                    <option selected="" value="ENGLISH">English
                                    </option><option value="AFRIKAANS">Afrikaans
                                    </option><option value="BRITISHENG">British English
                                    </option><option value="CHINESE">Chinese (Mandarin)
                                    </option><option value="CREOLE">Creole
                                    </option><option value="CZECH">Czech
                                    </option><option value="DANISH">Danish
                                    </option><option value="DUTCH">Dutch
                                    </option><option value="FINNISH">Finnish
                                    </option><option value="FRENCH">French
                                    </option><option value="FRENCHCAN">French Canadian
                                    </option><option value="GERMAN">German
                                    </option><option value="GREEK">Greek
                                    </option><option value="HEBREW">Hebrew
                                    </option><option value="HUNGARIAN">Hungarian
                                    </option><option value="ITALIAN">Italian
                                    </option><option value="JAPANESE">Japanese
                                    </option><option value="KOREAN">Korean
                                    </option><option value="LITHUANIAN">Lithuanian
                                    </option><option value="NORWEGIAN">Norwegian
                                    </option><option value="POLISH">Polish
                                    </option><option value="PORTUGUESE">Portuguese
                                    </option><option value="ROMANIAN">Romanian
                                    </option><option value="RUSSIAN">Russian
                                    </option><option value="SPANISH">Spanish
                                    </option><option value="SWEDISH">Swedish
                                    </option><option value="THAI">Thai
                                    </option><option value="TURKISH">Turkish
                                    </option><option value="UKRAINIAN">Ukrainian
                                    </option></select>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="section-2">
                            <div class="row">
                                <div class="col-sm-4">
                                    <span class="home-mls-title">Quick search by MLS ID</span>
                                    <form action="" name="search" method="post" style="margin-top: 10px">
                                        <input name="search" type="text" placeholder="Search" style="width: 100%;">
                                        <i class="fa fa-search search-icon"></i>
                                    </form>
                                </div>
                                <div class="col-sm-4">
                                    <span class="home-mls-title">Property Type</span>
                                    <select name="sPropertyType" class="selectfiletext" onchange="ChangeLang('ENGLISH')" style="width: 100%;margin-top: 10px">
                                        <option value="S">Single Family
                                        </option><option value="M">Condo / Town Home
                                        </option><option value="B">Mobile Home
                                        </option><option value="V">Vacant Land
                                        </option><option value="C">Commercial
                                        </option><option value="D">Multi-Family
                                        </option><option value="R">Rental</option>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <span class="home-mls-title">Cities</span>
                                    <select name="sCities" class="selectfiletext" onchange="ChangeLang('ENGLISH')" style="width: 100%;margin-top: 10px">
                                        <option value="Y00000">Single Family
                                        </option><option value="Y21344">Alachua
                                        </option><option value="Y26810">Alafaya
                                        </option><option value="Y21347">Alford
                                        </option><option value="Y26808">Alligator Point
                                        </option><option value="Y21351">Aloma
                                        </option><option value="Y21355">Altamonte Springs
                                        </option><option value="Y21356">Altha
                                        </option><option value="Y21357">Altoona
                                        </option><option value="Y21358">Alturas
                                        </option><option value="Y21359">Alva
                                        </option><option value="Y21361">Amelia Island
                                        </option><option value="Y21366">Anna Maria
                                        </option><option value="Y21367">Anthony
                                        </option><option value="Y21368">Apalachicola
                                        </option><option value="Y21370">Apollo Beach
                                        </option><option value="Y21372">Apopka
                                        </option><option value="Y21373">Arcadia
                                        </option><option value="Y21374">Archer
                                        </option><option value="Y21375">Argyle
                                        </option><option value="Y21376">Aripeka
                                        </option><option value="Y21380">Astatula
                                        </option><option value="Y21381">Astor
                                        </option><option value="Y21385">Atlantic Beach
                                        </option><option value="Y21387">Atlantis
                                        </option><option value="Y21388">Auburndale
                                        </option><option value="Y27293">Aventura
                                        </option><option value="Y21392">Aviation
                                        </option><option value="Y21393">Avon Park
                                        </option><option value="Y21396">Azalea Park
                                        </option><option value="Y21397">Babson Park
                                        </option><option value="Y21399">Bagdad
                                        </option><option value="Y21401">Baker
                                        </option><option value="Y21405">Bal Harbour
                                        </option><option value="Y21407">Baldwin
                                        </option><option value="Y21408">Balm
                                        </option><option value="Y21409">Barberville
                                        </option><option value="Y26796">Barefoot Bay
                                        </option><option value="Y21414">Bartow
                                        </option><option value="Y21415">Bascom
                                        </option><option value="Y21416">Basinger
                                        </option><option value="Y21419">Bay Harbor Islands
                                        </option><option value="Y21423">Bay Pines
                                        </option><option value="Y21429">Bayonet Point
                                        </option><option value="Y21447">Bell
                                        </option><option value="Y21448">Belle Glade
                                        </option><option value="Y21449">Belle Isle
                                        </option><option value="Y21450">Belleair
                                        </option><option value="Y21452">Belleair Beach
                                        </option><option value="Y21453">Belleair Bluffs
                                        </option><option value="Y21455">Belleair Shores
                                        </option><option value="Y21456">Belleview
                                        </option><option value="Y21457">Bellview
                                        </option><option value="Y21459">Beverly Hills
                                        </option><option value="Y21464">Big Pine Key
                                        </option><option value="Y21465">Big Torch Key
                                        </option><option value="Y21471">Biscayne Park
                                        </option><option value="Y21474">Blountstown
                                        </option><option value="Y21476">Boca Grande
                                        </option><option value="Y21477">Boca Raton
                                        </option><option value="Y21479">Bokeelia
                                        </option><option value="Y21481">Bonifay
                                        </option><option value="Y21486">Bonita Springs
                                        </option><option value="Y21487">Bostwick
                                        </option><option value="Y21489">Bowling Green
                                        </option><option value="Y21491">Boynton Beach
                                        </option><option value="Y21496">Braden River
                                        </option><option value="Y21497">Bradenton
                                        </option><option value="Y21499">Bradenton Beach
                                        </option><option value="Y21501">Bradley
                                        </option><option value="Y21502">Brandon
                                        </option><option value="Y21503">Branford
                                        </option><option value="Y21506">Briny Breezes
                                        </option><option value="Y21507">Bristol
                                        </option><option value="Y21510">Bronson
                                        </option><option value="Y21511">Brooker
                                        </option><option value="Y21513">Brooksville
                                        </option><option value="Y21517">Bruce
                                        </option><option value="Y21519">Bryceville
                                        </option><option value="Y21520">Buena Ventura Lakes
                                        </option><option value="Y21522">Bunnell
                                        </option><option value="Y21523">Bushnell
                                        </option><option value="Y21527">Callahan
                                        </option><option value="Y21530">Campbellton
                                        </option><option value="Y21531">Canal Point
                                        </option><option value="Y21532">Canaveral Air Station
                                        </option><option value="Y21533">Candler
                                        </option><option value="Y21534">Cantonment
                                        </option><option value="Y21535">Cape Canaveral
                                        </option><option value="Y21536">Cape Coral
                                        </option><option value="Y27560">Cape Haze
                                        </option><option value="003549">Cape San Blas
                                        </option><option value="Y21540">Captiva
                                        </option><option value="Y21544">Carl Fisher
                                        </option><option value="Y21546">Carol City
                                        </option><option value="Y21548">Carrabelle
                                        </option><option value="Y21549">Carrollwood
                                        </option><option value="Y21552">Caryville
                                        </option><option value="Y21553">Cassadaga
                                        </option><option value="Y21554">Casselberry
                                        </option><option value="Y21561">Cedar Key
                                        </option><option value="Y27124">Celebration
                                        </option><option value="Y21566">Center Hill
                                        </option><option value="Y21570">Century
                                        </option><option value="001913">Champions Gate
                                        </option><option value="Y21574">Chattahoochee
                                        </option><option value="Y21575">Chiefland
                                        </option><option value="Y21576">Chipley
                                        </option><option value="000669">Choctaw Beach
                                        </option><option value="Y21577">Chokoloskee
                                        </option><option value="Y21579">Christmas
                                        </option><option value="Y21580">Chuluota
                                        </option><option value="Y21583">Citra
                                        </option><option value="Y27138">Citrus Springs
                                        </option><option value="Y21588">City Of Sunrise
                                        </option><option value="000582">Clair Mel City
                                        </option><option value="Y21591">Clarksville
                                        </option><option value="Y21592">Clearwater
                                        </option><option value="Y28294">Clearwater Beach
                                        </option><option value="Y21598">Clermont
                                        </option><option value="Y21602">Clewiston
                                        </option><option value="Y21603">Cloud Lake
                                        </option><option value="Y21604">Cocoa
                                        </option><option value="Y21605">Cocoa Beach
                                        </option><option value="Y26887">Coconut Creek
                                        </option><option value="Y21609">Coconut Grove
                                        </option><option value="Y21613">Coleman
                                        </option><option value="Y21620">Conch Key
                                        </option><option value="Y26756">Cooper City
                                        </option><option value="Y21628">Coral Gables
                                        </option><option value="Y21633">Coral Springs
                                        </option><option value="Y21639">Cortez
                                        </option><option value="Y21641">Cottondale
                                        </option><option value="000092">Country Lakes
                                        </option><option value="Y21647">Crawfordville
                                        </option><option value="Y21650">Crescent Beach
                                        </option><option value="Y21651">Crescent City
                                        </option><option value="Y21652">Crestview
                                        </option><option value="Y21655">Cross City
                                        </option><option value="Y26758">Cross Creek
                                        </option><option value="Y21663">Crystal Beach
                                        </option><option value="Y21665">Crystal River
                                        </option><option value="Y21667">Crystal Springs
                                        </option><option value="Y21668">Cudjoe Key
                                        </option><option value="Y21671">Cutler Bay
                                        </option><option value="Y21672">Cypress
                                        </option><option value="Y21674">Cypress Gardens
                                        </option><option value="Y21678">Dade City
                                        </option><option value="Y21680">Dania
                                        </option><option value="Y28152">Dania Beach
                                        </option><option value="Y21681">Davenport
                                        </option><option value="Y21682">Davie
                                        </option><option value="Y27565">Davis Island
                                        </option><option value="Y21684">Day
                                        </option><option value="Y21688">Daytona Beach
                                        </option><option value="Y21690">Daytona Beach Shores
                                        </option><option value="Y21694">De Leon Springs
                                        </option><option value="Y21696">Debary
                                        </option><option value="Y21697">Deer Island
                                        </option><option value="Y21699">Deerfield Beach
                                        </option><option value="Y21692">Defuniak Springs
                                        </option><option value="Y21703">Deland
                                        </option><option value="Y21705">Delray Beach
                                        </option><option value="Y21707">Deltona
                                        </option><option value="Y21708">Destin
                                        </option><option value="Y21709">Dinsmore
                                        </option><option value="Y27507">Dona Vista
                                        </option><option value="003586">Doral
                                        </option><option value="Y21718">Dover
                                        </option><option value="Y21720">Dowling Park
                                        </option><option value="Y21744">Duck Key
                                        </option><option value="Y21745">Duette
                                        </option><option value="Y21746">Dundee
                                        </option><option value="Y21747">Dunedin
                                        </option><option value="Y21750">Dunnellon
                                        </option><option value="Y21751">Durant
                                        </option><option value="Y21755">E Rockland Key
                                        </option><option value="Y21756">Eagle Lake
                                        </option><option value="Y21758">Earleton
                                        </option><option value="Y21769">East Palatka
                                        </option><option value="Y21775">Eastlake Weir
                                        </option><option value="Y21776">Eastpoint
                                        </option><option value="Y21778">Eaton Park
                                        </option><option value="Y21780">Eatonville
                                        </option><option value="Y21781">Eau Gallie
                                        </option><option value="Y21783">Ebro
                                        </option><option value="Y21785">Edgewater
                                        </option><option value="Y21786">Edgewood
                                        </option><option value="Y21791">El Jobean
                                        </option><option value="Y21792">El Portal
                                        </option><option value="Y21795">Elkton
                                        </option><option value="Y21796">Ellenton
                                        </option><option value="Y21798">Eloise
                                        </option><option value="Y21800">Englewood
                                        </option><option value="Y21803">Enterprise
                                        </option><option value="Y21805">Estero
                                        </option><option value="Y21809">Eustis
                                        </option><option value="Y21812">Everglades City
                                        </option><option value="Y21814">Evinston
                                        </option><option value="Y21817">Fairfield
                                        </option><option value="Y27303">Fanning Springs
                                        </option><option value="Y21821">Fedhaven
                                        </option><option value="Y21822">Felda
                                        </option><option value="Y21823">Fellsmere
                                        </option><option value="Y21825">Fern Park
                                        </option><option value="Y21828">Fernandina Beach
                                        </option><option value="Y21829">Ferndale
                                        </option><option value="Y21849">Flagler Beach
                                        </option><option value="Y21851">Flamingo Lodge
                                        </option><option value="001085">Fleming Island
                                        </option><option value="Y21857">Florahome
                                        </option><option value="Y21858">Floral City
                                        </option><option value="Y21863">Florida City
                                        </option><option value="Y21882">Fort Lauderdale
                                        </option><option value="Y21883">Fort Mc Coy
                                        </option><option value="Y21884">Fort Meade
                                        </option><option value="Y21886">Fort Myers
                                        </option><option value="Y21888">Fort Myers Beach
                                        </option><option value="Y21889">Fort Ogden
                                        </option><option value="Y21890">Fort Pierce
                                        </option><option value="Y21891">Fort Walton Beach
                                        </option><option value="Y21892">Fort White
                                        </option><option value="Y21894">Fountain
                                        </option><option value="Y21896">Freeport
                                        </option><option value="Y21897">Frostproof
                                        </option><option value="Y26814">Fruit Cove
                                        </option><option value="Y21898">Fruitland Park
                                        </option><option value="Y21899">Fruitville
                                        </option><option value="Y21915">Gainesville
                                        </option><option value="Y21931">Geneva
                                        </option><option value="Y21932">Georgetown
                                        </option><option value="Y21934">Gibsonton
                                        </option><option value="Y21936">Glen Ridge
                                        </option><option value="Y21937">Glen Saint Mary
                                        </option><option value="Y21943">Golden Beach
                                        </option><option value="Y21944">Golden Gate
                                        </option><option value="Y21955">Goodland
                                        </option><option value="Y21957">Gotha
                                        </option><option value="Y21958">Goulds
                                        </option><option value="Y21960">Graceville
                                        </option><option value="Y21961">Graham
                                        </option><option value="Y21962">Grand Island
                                        </option><option value="Y21963">Grand Ridge
                                        </option><option value="Y21964">Grandin
                                        </option><option value="Y21965">Grant
                                        </option><option value="Y21969">Green Cove Springs
                                        </option><option value="Y26910">Greenacres
                                        </option><option value="Y21973">Greensboro
                                        </option><option value="Y21974">Greenville
                                        </option><option value="Y21977">Greenwood
                                        </option><option value="Y21979">Gretna
                                        </option><option value="Y21981">Grove City
                                        </option><option value="Y21983">Groveland
                                        </option><option value="Y21984">Gulf Breeze
                                        </option><option value="Y21986">Gulf Gate Branch
                                        </option><option value="Y21988">Gulf Hammock
                                        </option><option value="Y21991">Gulf Stream
                                        </option><option value="Y21992">Gulfport
                                        </option><option value="Y21999">Haines City
                                        </option><option value="Y22000">Haines Creek
                                        </option><option value="Y22003">Hallandale
                                        </option><option value="Y22005">Hallandale Beach
                                        </option><option value="Y22007">Hampton
                                        </option><option value="001785">Harmony
                                        </option><option value="Y26860">Harold
                                        </option><option value="Y22013">Hastings
                                        </option><option value="Y22014">Havana
                                        </option><option value="Y22015">Haverhill
                                        </option><option value="Y22016">Hawthorne
                                        </option><option value="Y27160">Heathrow
                                        </option><option value="Y22019">Hernando
                                        </option><option value="Y22020">Hernando Beach
                                        </option><option value="Y22026">Hialeah
                                        </option><option value="Y22029">Hialeah Gardens
                                        </option><option value="Y22032">Hiawassee
                                        </option><option value="Y22035">High Springs
                                        </option><option value="Y22036">Highland Beach
                                        </option><option value="Y22037">Highland City
                                        </option><option value="Y22044">Hilliard
                                        </option><option value="Y22046">Hillsboro Beach
                                        </option><option value="Y22050">Hobe Sound
                                        </option><option value="Y22051">Holder
                                        </option><option value="Y22052">Holiday
                                        </option><option value="Y22054">Hollister
                                        </option><option value="Y22055">Holly Hill
                                        </option><option value="Y22056">Hollywood
                                        </option><option value="Y22061">Holmes Beach
                                        </option><option value="Y22062">Holt
                                        </option><option value="Y22063">Homeland
                                        </option><option value="Y22064">Homestead
                                        </option><option value="Y22068">Homosassa
                                        </option><option value="Y22069">Homosassa Springs
                                        </option><option value="Y22070">Horseshoe Bch
                                        </option><option value="Y22071">Horseshoe Beach
                                        </option><option value="Y22072">Hosford
                                        </option><option value="Y22073">Howey In The Hills
                                        </option><option value="Y22074">Hudson
                                        </option><option value="Y27292">Hutchinson Island
                                        </option><option value="Y22083">Hypoluxo
                                        </option><option value="Y22085">Immokalee
                                        </option><option value="Y22086">Indialantic
                                        </option><option value="Y26919">Indian Creek
                                        </option><option value="001182">Indian Creek Village
                                        </option><option value="Y22087">Indian Harbor Beach
                                        </option><option value="Y22088">Indian Harbour Beach
                                        </option><option value="Y22090">Indian Lake Estates
                                        </option><option value="Y22092">Indian River Shores
                                        </option><option value="Y22096">Indian Rocks Beach
                                        </option><option value="Y22097">Indian Shores
                                        </option><option value="Y22098">Indiantown
                                        </option><option value="Y22100">Inglis
                                        </option><option value="Y22104">Intercession City
                                        </option><option value="Y22106">Interchange Square
                                        </option><option value="Y22107">Interlachen
                                        </option><option value="Y22109">Inverness
                                        </option><option value="Y22115">Islamorada
                                        </option><option value="Y22117">Island Grove
                                        </option><option value="Y22118">Istachatta
                                        </option><option value="Y22126">Jacksonville
                                        </option><option value="Y22128">Jacksonville Beach
                                        </option><option value="002510">Jacob
                                        </option><option value="Y22137">Jasper
                                        </option><option value="Y22143">Jay
                                        </option><option value="Y22144">Jennings
                                        </option><option value="Y22145">Jensen Beach
                                        </option><option value="003308">Jerome
                                        </option><option value="000712">Jonesville
                                        </option><option value="Y22152">Juno Beach
                                        </option><option value="Y22154">Jupiter
                                        </option><option value="000241">Jupiter Inlet Colony
                                        </option><option value="Y22156">Kathleen
                                        </option><option value="Y22157">Kenansville
                                        </option><option value="Y22158">Kendall
                                        </option><option value="Y22161">Kenneth City
                                        </option><option value="Y22163">Key Biscayne
                                        </option><option value="Y22165">Key Colony Beach
                                        </option><option value="Y22166">Key Largo
                                        </option><option value="Y22167">Key West
                                        </option><option value="Y22169">Keystone Heights
                                        </option><option value="Y22174">Kinard
                                        </option><option value="Y22175">Kissimmee
                                        </option><option value="Y22178">La Crosse
                                        </option><option value="Y22181">Labelle
                                        </option><option value="Y22182">Lacoochee
                                        </option><option value="Y22184">Lady Lake
                                        </option><option value="Y22187">Lake Alfred
                                        </option><option value="Y22188">Lake Buena Vista
                                        </option><option value="Y22189">Lake Butler
                                        </option><option value="Y22191">Lake City
                                        </option><option value="Y22192">Lake Clarke Shores
                                        </option><option value="Y22198">Lake Hamilton
                                        </option><option value="Y22199">Lake Harbor
                                        </option><option value="Y22200">Lake Helen
                                        </option><option value="Y22207">Lake Mary
                                        </option><option value="Y22212">Lake Panasoffkee
                                        </option><option value="Y22213">Lake Park
                                        </option><option value="Y22215">Lake Placid
                                        </option><option value="Y27146">Lake Suzy
                                        </option><option value="Y22223">Lake Wales
                                        </option><option value="Y22225">Lake Worth
                                        </option><option value="Y22227">Lakeland
                                        </option><option value="Y28136">Lakeshore
                                        </option><option value="001964">Lakewood Park
                                        </option><option value="001207">Lakewood Ranch
                                        </option><option value="Y22230">Lamont
                                        </option><option value="Y22231">Lanark Village
                                        </option><option value="Y22233">Land O Lakes
                                        </option><option value="Y22236">Lantana
                                        </option><option value="Y22237">Largo
                                        </option><option value="Y22241">Lauderdale By The Sea
                                        </option><option value="Y22243">Lauderdale Lakes
                                        </option><option value="Y22245">Lauderhill
                                        </option><option value="Y22246">Laurel
                                        </option><option value="Y22248">Laurel Hill
                                        </option><option value="Y22249">Lawtey
                                        </option><option value="Y26909">Lazy Lake
                                        </option><option value="Y22251">Lecanto
                                        </option><option value="Y22252">Lee
                                        </option><option value="Y22254">Leesburg
                                        </option><option value="Y22256">Lehigh Acres
                                        </option><option value="Y22261">Lighthouse Point
                                        </option><option value="Y22268">Lithia
                                        </option><option value="Y22270">Little Torch Key
                                        </option><option value="Y22271">Live Oak
                                        </option><option value="Y26856">Lk Forest
                                        </option><option value="Y22280">Lloyd
                                        </option><option value="Y22283">Lochloosa
                                        </option><option value="Y22284">Lockhart
                                        </option><option value="Y22287">Long Key
                                        </option><option value="Y22288">Longboat Key
                                        </option><option value="Y22289">Longwood
                                        </option><option value="Y22290">Lorida
                                        </option><option value="Y22291">Loughman
                                        </option><option value="Y22292">Lowell
                                        </option><option value="Y22294">Loxahatchee
                                        </option><option value="Y22298">Lulu
                                        </option><option value="Y22299">Lutz
                                        </option><option value="Y22300">Lynn Haven
                                        </option><option value="Y22305">Macclenny
                                        </option><option value="Y22310">Madeira Beach
                                        </option><option value="Y22314">Madison
                                        </option><option value="Y22319">Maitland
                                        </option><option value="Y22320">Malabar
                                        </option><option value="Y22322">Malone
                                        </option><option value="Y22323">Manalapan
                                        </option><option value="001847">Manatee Contract Branch
                                        </option><option value="Y22329">Mango
                                        </option><option value="Y22332">Marathon
                                        </option><option value="Y22337">Marco Island
                                        </option><option value="Y22338">Margate
                                        </option><option value="Y22340">Marianna
                                        </option><option value="Y22344">Mary Esther
                                        </option><option value="Y22345">Masaryktown
                                        </option><option value="Y22346">Mascotte
                                        </option><option value="Y22350">Matlacha
                                        </option><option value="002877">Matlacha Isles
                                        </option><option value="Y28198">Maxville
                                        </option><option value="Y22351">Mayo
                                        </option><option value="Y22359">Mc Alpin
                                        </option><option value="Y22360">Mc David
                                        </option><option value="Y22361">Mc Intosh
                                        </option><option value="Y22366">Medley
                                        </option><option value="Y22370">Melbourne
                                        </option><option value="Y22372">Melbourne Beach
                                        </option><option value="Y22374">Melbourne Village
                                        </option><option value="Y22375">Melrose
                                        </option><option value="000024">Melrose Vista
                                        </option><option value="Y22376">Merritt Island
                                        </option><option value="Y22378">Mexico Beach
                                        </option><option value="Y22388">Miami
                                        </option><option value="Y22391">Miami Beach
                                        </option><option value="Y22393">Miami Gardens
                                        </option><option value="Y22394">Miami Lakes
                                        </option><option value="Y22395">Miami Shores
                                        </option><option value="Y22399">Miami Springs
                                        </option><option value="Y22400">Micanopy
                                        </option><option value="Y22401">Micco
                                        </option><option value="Y22403">Miccosukee
                                        </option><option value="Y22410">Middle Torch Key
                                        </option><option value="Y22411">Middleburg
                                        </option><option value="Y22414">Midway
                                        </option><option value="Y22416">Milligan
                                        </option><option value="Y22417">Milton
                                        </option><option value="Y22418">Mims
                                        </option><option value="Y22419">Minneola
                                        </option><option value="Y22421">Miramar
                                        </option><option value="000296">Miramar Beach
                                        </option><option value="002383">Miromar Lakes
                                        </option><option value="Y22425">Molino
                                        </option><option value="Y22426">Monticello
                                        </option><option value="Y22427">Montverde
                                        </option><option value="Y22428">Moore Haven
                                        </option><option value="Y22429">Morriston
                                        </option><option value="Y22430">Mossy Head
                                        </option><option value="Y22431">Mount Dora
                                        </option><option value="Y22435">Mount Plymouth
                                        </option><option value="Y22434">Mt Pleasant
                                        </option><option value="Y22436">Mulberry
                                        </option><option value="Y22443">Myakka City
                                        </option><option value="Y22452">N Fort Myers
                                        </option><option value="Y22467">Naples
                                        </option><option value="Y22468">Naranja
                                        </option><option value="Y22480">Navarre
                                        </option><option value="Y27136">Neptune Beach
                                        </option><option value="Y22487">New Port Richey
                                        </option><option value="Y22492">New Smyrna Beach
                                        </option><option value="Y22494">Newberry
                                        </option><option value="Y22496">Niceville
                                        </option><option value="Y22497">Nichols
                                        </option><option value="Y22513">Nobleton
                                        </option><option value="Y22514">Nocatee
                                        </option><option value="Y22515">Nokomis
                                        </option><option value="Y22516">Noma
                                        </option><option value="Y22522">North Bay Village
                                        </option><option value="002217">North Cleveland
                                        </option><option value="Y22526">North Fort Myers
                                        </option><option value="Y22530">North Lauderdale
                                        </option><option value="Y22533">North Miami
                                        </option><option value="Y22536">North Miami Beach
                                        </option><option value="Y22539">North Palm Beach
                                        </option><option value="Y22540">North Port
                                        </option><option value="Y22542">North Redington Beach
                                        </option><option value="002934">North Venice
                                        </option><option value="Y22545">Northdale
                                        </option><option value="Y22558">O Brien
                                        </option><option value="Y22560">Oak Hill
                                        </option><option value="Y22565">Oakland
                                        </option><option value="Y22566">Oakland Park
                                        </option><option value="Y22570">Ocala
                                        </option><option value="Y22573">Ocean Ridge
                                        </option><option value="Y28207">Ochlockonee Bay
                                        </option><option value="Y22575">Ochopee
                                        </option><option value="Y22576">Ocklawaha
                                        </option><option value="Y22577">Ocoee
                                        </option><option value="Y22578">Odessa
                                        </option><option value="Y22580">Okahumpka
                                        </option><option value="Y22582">Okeechobee
                                        </option><option value="Y22585">Old Town
                                        </option><option value="Y22586">Oldsmar
                                        </option><option value="Y22588">Olustee
                                        </option><option value="Y22589">Olympia Heights
                                        </option><option value="Y22591">Ona
                                        </option><option value="Y22595">Opa Locka
                                        </option><option value="Y22601">Orange City
                                        </option><option value="Y22602">Orange Lake
                                        </option><option value="Y22603">Orange Park
                                        </option><option value="Y22606">Orange Springs
                                        </option><option value="000972">Orchid
                                        </option><option value="Y22611">Orlando
                                        </option><option value="Y22615">Ormond Beach
                                        </option><option value="Y22621">Osprey
                                        </option><option value="Y22622">Osteen
                                        </option><option value="Y22623">Otter Creek
                                        </option><option value="Y27400">Overstreet
                                        </option><option value="Y22625">Oviedo
                                        </option><option value="Y22626">Oxford
                                        </option><option value="Y22627">Ozona
                                        </option><option value="Y22628">Pace
                                        </option><option value="Y22632">Pahokee
                                        </option><option value="Y22633">Paisley
                                        </option><option value="Y22634">Palatka
                                        </option><option value="Y22635">Palm Bay
                                        </option><option value="Y22638">Palm Beach
                                        </option><option value="Y22639">Palm Beach Gardens
                                        </option><option value="Y22642">Palm Beach Shores
                                        </option><option value="Y22643">Palm City
                                        </option><option value="Y22644">Palm Coast
                                        </option><option value="Y22645">Palm Harbor
                                        </option><option value="Y22649">Palm Springs
                                        </option><option value="Y22652">Palma Ceia
                                        </option><option value="Y22655">Palmdale
                                        </option><option value="Y22656">Palmetto
                                        </option><option value="Y22657">Panacea
                                        </option><option value="Y22659">Panama City
                                        </option><option value="Y22660">Panama City Beach
                                        </option><option value="Y22663">Parkland
                                        </option><option value="Y22664">Parrish
                                        </option><option value="Y22667">Pass A Grille Beach
                                        </option><option value="Y22672">Paxton
                                        </option><option value="Y22676">Pembroke Park
                                        </option><option value="Y22677">Pembroke Pines
                                        </option><option value="Y22686">Penney Farms
                                        </option><option value="Y22688">Pensacola
                                        </option><option value="Y22689">Pensacola Beach
                                        </option><option value="Y22691">Perrine
                                        </option><option value="Y22693">Perry
                                        </option><option value="Y22694">Pierson
                                        </option><option value="Y22696">Pine Hills
                                        </option><option value="001463">Pinecrest
                                        </option><option value="Y22702">Pineland
                                        </option><option value="Y22703">Pinellas Park
                                        </option><option value="Y22705">Pinetta
                                        </option><option value="Y22707">Placida
                                        </option><option value="Y22708">Plant City
                                        </option><option value="Y22709">Plantation
                                        </option><option value="Y22720">Poinciana
                                        </option><option value="Y22721">Point Washington
                                        </option><option value="Y22722">Polk City
                                        </option><option value="Y22724">Pomona Park
                                        </option><option value="Y22729">Pompano Beach
                                        </option><option value="Y22731">Ponce De Leon
                                        </option><option value="Y22732">Ponce Inlet
                                        </option><option value="Y22733">Ponte Vedra
                                        </option><option value="Y22734">Ponte Vedra Beach
                                        </option><option value="Y22737">Port Charlotte
                                        </option><option value="Y22743">Port Orange
                                        </option><option value="Y22745">Port Richey
                                        </option><option value="Y22746">Port Saint Joe
                                        </option><option value="Y22747">Port Saint John
                                        </option><option value="Y22748">Port Saint Lucie
                                        </option><option value="Y22749">Port Salerno
                                        </option><option value="Y22768">Punta Gorda
                                        </option><option value="Y22770">Putnam Hall
                                        </option><option value="Y22773">Quincy
                                        </option><option value="Y22775">Raiford
                                        </option><option value="Y22778">Ramrod Key
                                        </option><option value="Y22782">Red Bay
                                        </option><option value="Y22783">Reddick
                                        </option><option value="Y22785">Redington Beach
                                        </option><option value="Y22786">Redington Shores
                                        </option><option value="Y21615">Renaissance
                                        </option><option value="003384">Reunion
                                        </option><option value="Y26734">Richland
                                        </option><option value="Y27150">Ridge Manor
                                        </option><option value="Y22791">Ridge Manor Estates
                                        </option><option value="Y22796">River Ranch
                                        </option><option value="Y22801">Riverview
                                        </option><option value="Y22803">Riviera Beach
                                        </option><option value="Y22804">Rockledge
                                        </option><option value="Y22806">Roseland
                                        </option><option value="Y23055">Rosemary Beach
                                        </option><option value="Y22807">Rotonda West
                                        </option><option value="Y22811">Royal Palm Beach
                                        </option><option value="Y22814">Rubonia
                                        </option><option value="Y22815">Ruskin
                                        </option><option value="Y22823">Safety Harbor
                                        </option><option value="Y22827">Saint Augustine
                                        </option><option value="Y22829">Saint Augustine Beach
                                        </option><option value="Y22831">Saint Cloud
                                        </option><option value="Y22832">Saint George Island
                                        </option><option value="Y22833">Saint James City
                                        </option><option value="Y23069">Saint Johns
                                        </option><option value="Y28153">Saint Lucie West
                                        </option><option value="Y22835">Saint Marks
                                        </option><option value="Y22840">Saint Pete Beach
                                        </option><option value="Y22837">Saint Petersburg
                                        </option><option value="Y28023">Saint Teresa
                                        </option><option value="Y22843">Salt Springs
                                        </option><option value="Y22846">San Antonio
                                        </option><option value="Y22847">San Mateo
                                        </option><option value="Y22849">Sanderson
                                        </option><option value="Y22850">Sandestin
                                        </option><option value="Y22852">Sanford
                                        </option><option value="Y22853">Sanibel
                                        </option><option value="Y22857">Santa Rosa Beach
                                        </option><option value="Y22859">Sarasota
                                        </option><option value="Y22861">Satellite Beach
                                        </option><option value="Y22862">Satsuma
                                        </option><option value="Y22865">Scottsmoor
                                        </option><option value="Y22866">Sea Ranch Lakes
                                        </option><option value="Y22870">Sebastian
                                        </option><option value="Y22871">Sebring
                                        </option><option value="Y22873">Seffner
                                        </option><option value="Y22875">Seminole
                                        </option><option value="Y22882">Seville
                                        </option><option value="Y22883">Sewalls Point
                                        </option><option value="Y22886">Shady Hills
                                        </option><option value="Y22887">Shalimar
                                        </option><option value="Z00001">Shark Key
                                        </option><option value="000172">Sidell
                                        </option><option value="Y22891">Siesta Key
                                        </option><option value="Y22894">Silver Springs
                                        </option><option value="Y27328">Singer Island
                                        </option><option value="Y22899">Sneads
                                        </option><option value="Y22906">Sopchoppy
                                        </option><option value="Y22907">Sorrento
                                        </option><option value="Y22908">South Bay
                                        </option><option value="Y22911">South Daytona
                                        </option><option value="Y22922">South Miami
                                        </option><option value="Y22926">South Palm Beach
                                        </option><option value="Y22927">South Pasadena
                                        </option><option value="Y22942">Southport
                                        </option><option value="001279">Southwest Ranches
                                        </option><option value="Y22950">Sparr
                                        </option><option value="Y22951">Spring Hill
                                        </option><option value="Y23016">Starke
                                        </option><option value="Y23023">Steinhatchee
                                        </option><option value="Y23024">Stock Island
                                        </option><option value="Y23025">Stuart
                                        </option><option value="Y23030">Sugarloaf
                                        </option><option value="Y23032">Sugarloaf Key
                                        </option><option value="Y23036">Sumatra
                                        </option><option value="Y23037">Summerfield
                                        </option><option value="Y23038">Summerland Key
                                        </option><option value="Y23039">Sumterville
                                        </option><option value="Y23040">Sun City
                                        </option><option value="Y23041">Sun City Center
                                        </option><option value="000016">Sunny Isles Beach
                                        </option><option value="Y23056">Sunrise
                                        </option><option value="Y23064">Surfside
                                        </option><option value="Y23066">Suwannee
                                        </option><option value="Y23073">Tallahassee
                                        </option><option value="Y23075">Tamarac
                                        </option><option value="Y23079">Tampa
                                        </option><option value="000581">Tampa Palms
                                        </option><option value="Y23082">Tangerine
                                        </option><option value="Y23084">Tarpon Springs
                                        </option><option value="Y23087">Tavares
                                        </option><option value="Y23089">Tavernier
                                        </option><option value="Y23090">Telogia
                                        </option><option value="Y23092">Temple Terrace
                                        </option><option value="Y23095">Tequesta
                                        </option><option value="Y23096">Terra Ceia
                                        </option><option value="001808">Terra Ceia Island
                                        </option><option value="Y27933">The Villages
                                        </option><option value="Y23098">Thonotosassa
                                        </option><option value="Y23100">Tierra Verde
                                        </option><option value="Y23102">Tiger Point
                                        </option><option value="Y23104">Titusville
                                        </option><option value="Y23118">Treasure Island
                                        </option><option value="Y23120">Trenton
                                        </option><option value="Y23121">Trilby
                                        </option><option value="000887">Trinity
                                        </option><option value="Y23122">Tropic
                                        </option><option value="Y23133">Umatilla
                                        </option><option value="002175">University Of Tampa
                                        </option><option value="Y23152">University Park
                                        </option><option value="Y23157">Valparaiso
                                        </option><option value="Y23158">Valrico
                                        </option><option value="Y23163">Venice
                                        </option><option value="Y23166">Venus
                                        </option><option value="Y23167">Vernon
                                        </option><option value="Y23168">Vero Beach
                                        </option><option value="Y27399">Viera
                                        </option><option value="Y23175">Village Of Golf
                                        </option><option value="003005">Village Of Palmetto Bay
                                        </option><option value="Y23176">Virginia Gardens
                                        </option><option value="Y23179">W Cocoa
                                        </option><option value="Y23189">Wabasso
                                        </option><option value="Y23190">Wacissa
                                        </option><option value="Y23191">Wahneta
                                        </option><option value="Y23192">Wakulla Springs
                                        </option><option value="Y23196">Waldo
                                        </option><option value="Y23197">Walnut Hill
                                        </option><option value="Y23198">Warm Mineral Springs
                                        </option><option value="003200">Watersound
                                        </option><option value="Y23201">Wauchula
                                        </option><option value="Y23202">Wausau
                                        </option><option value="Y23203">Waverly
                                        </option><option value="Y23204">Webster
                                        </option><option value="Y23205">Weeki Wachee
                                        </option><option value="Y23206">Weirsdale
                                        </option><option value="Y23209">Welaka
                                        </option><option value="Y23210">Wellborn
                                        </option><option value="Y23211">Wellington
                                        </option><option value="Y23213">Wesley Chapel
                                        </option><option value="Y23237">West Beach Station
                                        </option><option value="Y23225">West Hollywood
                                        </option><option value="Y27390">West Melbourne
                                        </option><option value="Y23232">West Miami
                                        </option><option value="Y23234">West Palm Beach
                                        </option><option value="001257">Westchase
                                        </option><option value="Y23244">Weston
                                        </option><option value="Y23248">Westville
                                        </option><option value="Y23249">Wewahitchka
                                        </option><option value="Y23252">White Springs
                                        </option><option value="Y27743">Wilbur By The Sea
                                        </option><option value="Y23257">Wildwood
                                        </option><option value="Y23261">Williston
                                        </option><option value="Y23263">Wilton Manors
                                        </option><option value="Y23265">Wimauma
                                        </option><option value="Y23266">Windermere
                                        </option><option value="Y23268">Winter Beach
                                        </option><option value="Y23269">Winter Garden
                                        </option><option value="Y23270">Winter Haven
                                        </option><option value="Y23272">Winter Park
                                        </option><option value="Y23273">Winter Springs
                                        </option><option value="Y23279">Woodville
                                        </option><option value="Y23281">Worthington Springs
                                        </option><option value="Y23285">Yalaha
                                        </option><option value="Y23286">Yankeetown
                                        </option><option value="Y23289">Yeehaw Junction
                                        </option><option value="Y23290">Youngstown
                                        </option><option value="Y23292">Yulee
                                        </option><option value="Y23294">Zellwood
                                        </option><option value="Y23295">Zephyrhills
                                        </option><option value="Y23297">Zolfo Springs</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="section-3">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="col-sm-6" style="padding-left: 0px;">
                                        <span class="home-price-title">Minimum Price</span>
                                        <select name="MinimumValue" class="selectfiletext" onchange="ChangeLang('ENGLISH')" style="width: 100%;margin-top: 4px">
                                            <option selected="" value="0">$0
                                            </option><option value="1000">$1,000
                                            </option><option value="2000">$2,000
                                            </option><option value="5000">$5,000
                                            </option><option value="10000">$10,000
                                            </option><option value="20000">$20,000
                                            </option><option value="30000">$30,000
                                            </option><option value="40000">$40,000
                                            </option><option value="50000">$50,000
                                            </option><option value="60000">$60,000
                                            </option><option value="70000">$70,000
                                            </option><option value="80000">$80,000
                                            </option><option value="90000">$90,000
                                            </option><option value="100000">$100,000
                                            </option><option value="125000">$125,000
                                            </option><option value="150000">$150,000
                                            </option><option value="175000">$175,000
                                            </option><option value="200000">$200,000
                                            </option><option value="225000">$225,000
                                            </option><option value="250000">$250,000
                                            </option><option value="275000">$275,000
                                            </option><option value="300000">$300,000
                                            </option><option value="325000">$325,000
                                            </option><option value="350000">$350,000
                                            </option><option value="375000">$375,000
                                            </option><option value="400000">$400,000
                                            </option><option value="425000">$425,000
                                            </option><option value="450000">$450,000
                                            </option><option value="475000">$475,000
                                            </option><option value="500000">$500,000
                                            </option><option value="750000">$750,000
                                            </option><option value="1000000">$1,000,000
                                            </option><option value="1250000">$1,250,000
                                            </option><option value="1500000">$1,500,000
                                            </option><option value="1750000">$1,750,000
                                            </option><option value="2000000">$2,000,000
                                            </option><option value="2250000">$2,250,000
                                            </option><option value="2500000">$2,500,000
                                            </option><option value="2750000">$2,750,000
                                            </option><option value="3000000">$3,000,000
                                            </option><option value="3250000">$3,250,000
                                            </option><option value="3500000">$3,500,000
                                            </option><option value="3750000">$3,750,000
                                            </option><option value="4000000">$4,000,000
                                            </option><option value="4250000">$4,250,000
                                            </option><option value="4500000">$4,500,000
                                            </option><option value="4750000">$4,750,000
                                            </option><option value="5000000">$5,000,000</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-6" style="padding-right: 0px;">
                                        <span class="home-price-title">Maximum Price</span>
                                        <select name="MaximumValue" class="selectfiletext" onchange="ChangeLang('ENGLISH')" style="width: 100%;margin-top: 4px">
                                            <option value="0">$0
                                            </option><option value="1000">$1,000
                                            </option><option value="2000">$2,000
                                            </option><option value="5000">$5,000
                                            </option><option value="10000">$10,000
                                            </option><option value="20000">$20,000
                                            </option><option value="30000">$30,000
                                            </option><option value="40000">$40,000
                                            </option><option value="50000">$50,000
                                            </option><option value="60000">$60,000
                                            </option><option value="70000">$70,000
                                            </option><option value="80000">$80,000
                                            </option><option value="90000">$90,000
                                            </option><option value="100000">$100,000
                                            </option><option value="125000">$125,000
                                            </option><option value="150000">$150,000
                                            </option><option value="175000">$175,000
                                            </option><option value="200000">$200,000
                                            </option><option value="225000">$225,000
                                            </option><option value="250000">$250,000
                                            </option><option value="275000">$275,000
                                            </option><option value="300000">$300,000
                                            </option><option value="325000">$325,000
                                            </option><option value="350000">$350,000
                                            </option><option value="375000">$375,000
                                            </option><option value="400000">$400,000
                                            </option><option value="425000">$425,000
                                            </option><option value="450000">$450,000
                                            </option><option value="475000">$475,000
                                            </option><option value="500000">$500,000
                                            </option><option value="750000">$750,000
                                            </option><option value="1000000">$1,000,000
                                            </option><option value="1250000">$1,250,000
                                            </option><option value="1500000">$1,500,000
                                            </option><option value="1750000">$1,750,000
                                            </option><option value="2000000">$2,000,000
                                            </option><option value="2250000">$2,250,000
                                            </option><option value="2500000">$2,500,000
                                            </option><option value="2750000">$2,750,000
                                            </option><option value="3000000">$3,000,000
                                            </option><option value="3250000">$3,250,000
                                            </option><option value="3500000">$3,500,000
                                            </option><option value="3750000">$3,750,000
                                            </option><option value="4000000">$4,000,000
                                            </option><option value="4250000">$4,250,000
                                            </option><option value="4500000">$4,500,000
                                            </option><option value="4750000">$4,750,000
                                            </option><option value="5000000">$5,000,000
                                            </option><option selected="" value="99999999999">None</option>
                                        </select>
                                    </div>

                                </div>
                                <div class="col-sm-4">
                                    <div class="col-sm-6" style="padding-left: 0px;">
                                        <span class="home-price-title">Minimum Bedrooms</span>
                                        <select name="bedroomValue" class="selectfiletext" onchange="ChangeLang('ENGLISH')" style="width: 100%;margin-top: 4px">
                                            <option selected="" value="0">Any
                                            </option><option value="1">1
                                            </option><option value="2">2
                                            </option><option value="3">3
                                            </option><option value="4">4
                                            </option><option value="5">5
                                            </option><option value="6">6</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-6" style="padding-right: 0px;">
                                        <span class="home-price-title">Maximum Bathrooms</span>
                                        <select name="bathroomValue" class="selectfiletext" onchange="ChangeLang('ENGLISH')" style="width: 100%;margin-top: 4px">
                                            <option selected="" value="0">Any
                                            </option><option value="1">1
                                            </option><option value="2">2
                                            </option><option value="3">3
                                            </option><option value="4">4
                                            </option><option value="5">5
                                            </option><option value="6">6</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="col-sm-6" style="padding-left: 0px;">
                                        <span class="home-price-title">Minimum Building...</span>
                                        <select name="building" class="selectfiletext" onchange="ChangeLang('ENGLISH')" style="width: 100%;margin-top: 4px">
                                                <option selected="" value="0">Any
                                                </option><option value="500">500
                                                </option><option value="600">600
                                                </option><option value="700">700
                                                </option><option value="800">800
                                                </option><option value="900">900
                                                </option><option value="1000">1000
                                                </option><option value="1100">1100
                                                </option><option value="1200">1200
                                                </option><option value="1300">1300
                                                </option><option value="1400">1400
                                                </option><option value="1500">1500
                                                </option><option value="1600">1600
                                                </option><option value="1700">1700
                                                </option><option value="1800">1800
                                                </option><option value="1900">1900
                                                </option><option value="2000">2000
                                                </option><option value="2100">2100
                                                </option><option value="2200">2200
                                                </option><option value="2300">2300
                                                </option><option value="2400">2400
                                                </option><option value="2500">2500
                                                </option><option value="2600">2600
                                                </option><option value="2700">2700
                                                </option><option value="2800">2800
                                                </option><option value="2900">2900
                                                </option><option value="3000">3000
                                                </option><option value="3100">3100
                                                </option><option value="3200">3200
                                                </option><option value="3300">3300
                                                </option><option value="3400">3400
                                                </option><option value="3500">3500
                                                </option><option value="3600">3600
                                                </option><option value="3700">3700
                                                </option><option value="3800">3800
                                                </option><option value="3900">3900
                                                </option><option value="4000">4000
                                                </option><option value="4100">4100
                                                </option><option value="4200">4200
                                                </option><option value="4300">4300
                                                </option><option value="4400">4400
                                                </option><option value="4500">4500
                                                </option><option value="4600">4600
                                                </option><option value="4700">4700
                                                </option><option value="4800">4800
                                                </option><option value="4900">4900
                                                </option><option value="5000">5000
                                                </option><option value="10000">10000
                                                </option><option value="15000">15000
                                                </option><option value="20000">20000
                                                </option><option value="25000">25000
                                                </option><option value="30000">30000
                                                </option><option value="35000">35000
                                                </option><option value="40000">40000
                                                </option><option value="45000">45000
                                                </option><option value="50000">50000</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-6" style="padding-right: 0px;">
                                        <span class="home-price-title">Minimum Land Acres</span>
                                        <select name="bathroomValue" class="selectfiletext" onchange="ChangeLang('ENGLISH')" style="width: 100%;margin-top: 4px">
                                                <option value="0">Any
                                                </option><option value="0.25">   0.25
                                                </option><option value="0.50">   0.50
                                                </option><option value="0.75">   0.75
                                                </option><option value="1.00">   1.00
                                                </option><option value="2.00">   2.00
                                                </option><option value="3.00">   3.00
                                                </option><option value="4.00">   4.00
                                                </option><option value="5.00">   5.00
                                                </option><option value="6.00">   6.00
                                                </option><option value="7.00">   7.00
                                                </option><option value="8.00">   8.00
                                                </option><option value="9.00">   9.00
                                                </option><option value="10.00">  10.00
                                                </option><option value="20.00">  20.00
                                                </option><option value="30.00">  30.00
                                                </option><option value="40.00">  40.00
                                                </option><option value="50.00">  50.00
                                                </option><option value="60.00">  60.00
                                                </option><option value="70.00">  70.00
                                                </option><option value="80.00">  80.00
                                                </option><option value="90.00">  90.00
                                                </option><option value="100.00"> 100.00</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="section-4">
                            <span class="home-price-title">Property Features</span><br>
                            <form action="#" method="get" style="margin-top: 10px;letter-spacing: 1px;">
                                <div class="waterfront left" style="width: 17%;">
                                    <input type="checkbox" name="vehicle" value="Bike"> Waterfront property
                                </div>
                                <div class="fireplace left" style="width: 13%;">
                                    <input type="checkbox" name="vehicle" value="Bike"> Fireplace(s)
                                </div>
                                <div class="gasheating left" style="width: 14%;">
                                    <input type="checkbox" name="vehicle" value="Bike"> Gas heating
                                </div>
                                <div class="swimming left" style="width: 15%;">
                                    <input type="checkbox" name="vehicle" value="Bike" checked> Swimming pool
                                </div>
                                <div class="community left" style="width: 24%;">
                                    <input type="checkbox" name="vehicle" value="Bike"> Community swimming pool(s)
                                </div>
                                <div class="central-air left">
                                    <input type="checkbox" name="vehicle" value="Bike"> Central air conditioning
                                </div>
                                <div class="clear"></div>
                            </form>
                        </div>
                        <div class="section-5">
                            <div class="row">
                                <div class="col-sm-4">
                                    <span class="home-price-title left">Display Thumbnail Photos : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                                    <form action="#" method="get" class="left">
                                        <input type="radio" name="selectbox" value="Y" checked>Yes &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        <input type="radio" name="selectbox" value="N">No
                                    </form>
                                    <div class="clear"></div>
                                </div>
                                <div class="col-sm-4"></div>
                                <div class="col-sm-4 col-sm-offset-4">
                                    <div class="col-sm-6" style="padding-left: 0px;">
                                        <button type="button" value="Search" class="search-btn">Search</button>
                                    </div>
                                    <div class="col-sm-6" style="padding-right: 0px;">
                                        <button type="button" value="Reset" class="reset-btn">Reset</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Header Section -->
</body>

